const langArr = {
    "en":  {
        "Unlimited_Access": "Unlimited Access<br>to All Features",
        "Unlimited_documents": "Unlimited documents",
        "Count_mode": "Count mode",
        "Text_recognition_OCR": "Text recognition (OCR)",
        "Monthly": "Monthly",
        "price_per_month": "per month",
        "DAYS_FREE": "3 DAYS FREE",
        "price_month": "/month",
        "Annually": "Annually",
        "discount": "-83%",
        "price_per_year": "per year",
        "MOST_POPULAR": "MOST POPULAR",
        "Continue": "Continue",
        "Auto-renewable": "Auto-renewable. Cancel anytime.",
        "Terms_of_Use": "Terms of Use",
        "Restore": "Restore",
        "Privacy_Policy": "Privacy Policy"
    }, 
    "es": {
        "Unlimited_Access": "Acceso ilimitado<br>a todas las funciones",
        "Unlimited_documents": "Documentos ilimitados",
        "Count_mode": "Modo de recuento",
        "Text_recognition_OCR": "Reconocimiento de texto (OCR)",
        "Monthly": "Mensual",
        "price_per_month": "por mes",
        "DAYS_FREE": "3 DÍAS GRATIS",
        "price_month": "/mes",
        "Annually": "Anual",
        "discount": "-83%",
        "price_per_year": "por año",
        "MOST_POPULAR": "LO MÁS PEDIDO",
        "Continue": "Continuar",
        "Auto-renewable": "Renovable automáticamente. Cancela cuando quieras.",
        "Terms_of_Use": "Términos de uso",
        "Restore": "Restablecer",
        "Privacy_Policy": "Política de privacidad"  
    }, 
    "fr": {
        "Unlimited_Access": "Accès illimité<br>à toutes les fonctionnalités",
        "Unlimited_documents": "Documents illimités",
        "Count_mode": "Mode décompte",
        "Text_recognition_OCR": "Reconnaissance de texte (OCR)",
        "Monthly": "Tous les mois",
        "price_per_month": "par mois",
        "DAYS_FREE": "3 JOURS GRATUITS",
        "price_month": "/mois",
        "Annually": "Tous les ans",
        "discount": "-83%",
        "price_per_year": "par an",
        "MOST_POPULAR": "LE PLUS POPULAIRE",
        "Continue": "Continuer",
        "Auto-renewable": "Renouvelable automatiquement. Annulez à tout moment.",
        "Terms_of_Use": "Conditions d'utilisation",
        "Restore": "Restaurer",
        "Privacy_Policy": "Politique de confidentialité"
    }, 
    "ja": {
        "Unlimited_Access": "全ての機能へ<br>無制限アクセス",
        "Unlimited_documents": "無制限のドキュメント",
        "Count_mode": "カウントモード",
        "Text_recognition_OCR": "テキスト認識 (OCR)",
        "Monthly": "月次",
        "price_per_month": "/月",
        "DAYS_FREE": "3日間無料",
        "price_month": "/か月",
        "Annually": "年次",
        "discount": "-83%",
        "price_per_year": "/年",
        "MOST_POPULAR": "一番人気",
        "Continue": "続行する",
        "Auto-renewable": "自動更新可能。いつでもキャンセル可能。",
        "Terms_of_Use": "利用規約",
        "Restore": "復元する",
        "Privacy_Policy": "プライバシーポリシー"
    }, 
    "nl": {
        "Unlimited_Access": "Onbeperkte toegang<br>tot alle functies",
        "Unlimited_documents": "Onbeperkt aantal documenten",
        "Count_mode": "Aantal modus",
        "Text_recognition_OCR": "Gratis tekstherkenning (OCR)",
        "Monthly": "Maandelijks",
        "price_per_month": "per maand",
        "DAYS_FREE": "3 DAGEN GRATIS",
        "price_month": "/maand",
        "Annually": "Jaarlijks",
        "discount": "-83%",
        "price_per_year": "per jaar",
        "MOST_POPULAR": "MEEST POPULAIR",
        "Continue": "Doorgaan",
        "Auto-renewable": "Automatisch verlengbaar. Altijd annuleren.",
        "Terms_of_Use": "Gebruiksvoorwaarden",
        "Restore": "Herstellen",
        "Privacy_Policy": "Privacybeleid"
    }, 
    "ru": {
        "Unlimited_Access": "Неограниченный доступ<br>ко всем функциям",
        "Unlimited_documents": "Любое количество документов",
        "Count_mode": "Режим «Подсчет»",
        "Text_recognition_OCR": "Распознавание текста (OCR)",
        "Monthly": "1 месяц",
        "price_per_month": "в месяц",
        "DAYS_FREE": "3 ДНЯ БЕСПЛАТНО",
        "price_month": "/месяц",
        "Annually": "1 год",
        "discount": "-83%",
        "price_per_year": "в год",
        "MOST_POPULAR": "ПОПУЛЯРНОЕ",
        "Continue": "Продолжить",
        "Auto-renewable": "Автопродление. Отмена в любое время.",
        "Terms_of_Use": "Условия использования",
        "Restore": "Восстановить",
        "Privacy_Policy": "Конфиденциальность"
    },
    "zh": {
        "Unlimited_Access": "无限制使用<br>所有功能",
        "Unlimited_documents": "文档无限制",
        "Count_mode": "计数模式",
        "Text_recognition_OCR": "文本识别（OCR）",
        "Monthly": "每月",
        "price_per_month": "<strong>{{price}}</strong>每月<br>",
        "DAYS_FREE": "3日免费",
        "price_month": "/月",
        "Annually": "包年",
        "discount": "-83%",
        "price_per_year": "每年",
        "MOST_POPULAR": "最热门",
        "Continue": "继续",
        "Auto-renewable": "自动续订。可随时取消。",
        "Terms_of_Use": "使用条款",
        "Restore": "恢复",
        "Privacy_Policy": "隐私政策"
    }, 
}